# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Valentin Dzhankhotov
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Valentin Dzhankhotov's personal website.
  Dr. Dzhankhotov is an experienced front-end developer with strong background
  in power electronics and electric drives.
  He has a number of publications in premium industrial magazines. Visit this
  website to watch Valentin's portfolio and contact him.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

github_username: vushe
codepen_username: vushe
linkedin_username: valentin-dzhankhotov
googleacademy_userid: 3esuo7IAAAAJ

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed

host: 0.0.0.0
port: 4000

# Use production for production
stage: production

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


exclude: ['README.md', 'run.bash']